name: Bug Report
description: Open a bug report
title: "[Bug] "
labels: ["Potential Bug", "To Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please contact the Matomo community forum for questions: https://forum.matomo.org/
        If this bug is regarding a premium plugin you purchased on plugins.matomo.org, please email shop@matomo.org instead of creating a bug report here.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us what happens instead of the expected behavior.
      placeholder: Tell us what you see, e.g. "An error messaged shows when I visit Overview under Visitors"
    validations:
      required: true
  - type: textarea
    id: what-should-actually-happen
    attributes:
      label: What should happen?
      description: Please tell us what should happen. How has this issue affected you? What are you trying to accomplish?
      placeholder: Tell us what you expect to see, e.g. "I should see Visits Over Time and Visits Overview"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can this be reproduced?
      description: For UI bugs, please try to reproduce that on our Demo (https://demo.matomo.cloud). If possible, please include the URLs and steps how to reproduce it there. For other bugs or UI bugs that can't be reproduced on Demo, please include any relevant URLs or commands you are using that may help us to reproduce the bug.
      placeholder: Steps to reproduce, e.g. "Go to [Matomo-URL] > Click on Visitors > Click Overview"
    validations:
      required: true
  - type: input
    id: customer-website-name
    attributes:
      label: Website Name
      description: Website Name
    validations:
      required: false
  - type: dropdown
    id: installation
    attributes:
      label: On Premise or Cloud
      multiple: false
      options:
        - On Premise
        - Cloud
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      options:
        - 1 - Critical
        - 2 - High
        - 3 - Medium
        - 4 - Low
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Matomo version
      description: What version of Matomo are you running?
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What version of PHP are you running?
    validations:
      required: false
  - type: input
    id: server-os
    attributes:
      label: Server operating system
      description: What server operating system are you using?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
        - Not applicable (e.g. an API call etc.)
  - type: input
    id: machine-os
    attributes:
      label: Computer operating system
      description: What operating system are you using on your computer?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: code
    attributes:
      label: Validations
      description: "Before submitting the issue, please make sure you do the following:"
      options:
        - label: Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
          required: true
        - label: Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
          required: true
        - label: The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.
          required: true
